submitit_folder: '${savedir}/submitit'
timeout_min: 4320
cpus_per_task: 8
gpus_per_node: 1
tasks_per_node: 1
mem_gb: 64
nodes: 1
name: '${project}'
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
comment: null
constraint: null
exclude: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
max_num_timeout: 0
setup: null
