##########
# launcher
##########
hydra:
  job:
    name: '${name}'
    env_set:
      OMP_NUM_THREADS: '1'
      RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE: '1'
  run:
    dir: '${savedir}'
  sweep:
    dir: '${dproject}/sweep'

##########
# wandb
##########
wandb:  # wandb settings
  enable: false
  project: '${project}'
  name: '${name}'
  entity: '${oc.env:USER}'

##########
# training
##########
early_stopping:
    monitor: 'val_acc'
    mode: 'max'
debug: false
seed: 0
precision: 16
limit_val_batches: 1.0
batch_size: 32
grad_clip_norm: 10
collate_fn: 'auto'  # use 'ignore' to pass an identity collate and define featurize instead
max_steps: 1000
log_every_n_steps: 100
val_check_interval: 100
flush_logs_every_n_steps: 100
gpus: 1
strategy: null
test_only: false
autoresume: false
ckpt_path: '${savedir}/latest.ckpt'
learning_rate: 0.00001
val_sample_size: 10
num_rollouts: 1000


##########
# naming
##########
name: '${model}-${suffix}'
suffix: 'default'
model: 'mymodel'
project: 'messenger-dynamics'
savedir: '${dproject}/${name}'
dproject: '${oc.env:PWD}/saves'
frollout: '${oc.env:PWD}/saves/short_state_{}_rollouts.pt'

##########
# model params 
##########
dhid: 300

git:
  enable: false
s3:
  enable: false
